services:
  - type: web
    name: questlog-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /api/users/1
    envVars:
      - key: PORT
        value: 8080
